// Copyright 2026 Mark Boykin
// SPDX-License-Identifier: MIT OR Apache-2.0

//! Penrose aperiodic-tiling layout.
//!
//! Two variants:
//!
//! - [`PenroseVariant::Rhombus`] (P3) — thin + thick golden rhombi.
//!   Smoother visual texture, more mathematically uniform. Default.
//! - [`PenroseVariant::KiteDart`] (P2) — kite + dart tiles. Chunkier
//!   texture, more distinct local motifs.
//!
//! Both are generated by recursive Robinson-triangle subdivision (each
//! rhombus/kite/dart decomposes into two triangles with golden-ratio
//! subdivision rules). After `n` deflations, tile vertices are collected
//! deduplicated and sorted in a deterministic center-out order; nodes
//! are placed one per vertex.
//!
//! Node-to-vertex assignment strategy and unused-vertex policy are
//! exposed as config surfaces per the Step-5 configurability principle.
//! The first pass ships `PreservedOrder` assignment; advanced strategies
//! (graphlet / domain / UDC / edge-based) are tracked as future
//! enrichment.

use std::collections::HashMap;
use std::hash::Hash;

use euclid::default::{Point2D, Vector2D};
use serde::{Deserialize, Serialize};

use super::{Layout, LayoutExtras, StaticLayoutState};
use crate::camera::CanvasViewport;
use crate::scene::CanvasSceneInput;

const PHI: f32 = 1.618_034;
const INV_PHI: f32 = 0.618_034;

/// Which Penrose tiling variant to generate.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum PenroseVariant {
    /// P3 — thin + thick golden rhombi. Smoother, more uniform.
    Rhombus,
    /// P2 — kite + dart. Chunkier, more distinct local motifs.
    KiteDart,
}

impl Default for PenroseVariant {
    fn default() -> Self {
        Self::Rhombus
    }
}

/// How many deflation steps to apply.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum SubdivisionCount {
    /// Smallest depth such that vertex count ≥ node count. Default.
    Auto,
    /// Explicit depth; useful for artistic control and regression tests.
    Explicit(u8),
}

impl Default for SubdivisionCount {
    fn default() -> Self {
        Self::Auto
    }
}

/// How to assign nodes to tiling vertices.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum NodeAssignmentStrategy {
    /// Center-out spiral ordering. Stable across graph mutations; nodes
    /// near in insert order end up near in space. Ships first-pass.
    PreservedOrder,
    /// Group nodes onto nearby vertices by graphlet membership.
    /// *First-pass: falls back to `PreservedOrder`.*
    GraphletAware,
    /// Group nodes onto nearby vertices by registrable domain (read
    /// from `LayoutExtras::domain_by_node`).
    /// *First-pass: falls back to `PreservedOrder`.*
    DomainClustered,
    /// Group nodes onto nearby vertices by UDC classification path
    /// (via `LayoutExtras::axis_value_by_node`).
    /// *First-pass: falls back to `PreservedOrder`.*
    UdcClustered,
    /// Group nodes onto nearby vertices by edge connectivity.
    /// *First-pass: falls back to `PreservedOrder`.*
    EdgeAffinity,
}

impl Default for NodeAssignmentStrategy {
    fn default() -> Self {
        Self::PreservedOrder
    }
}

/// How to handle the (typical) case where the tiling has more vertices
/// than the graph has nodes.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum UnusedVertexPolicy {
    /// Unused vertices remain empty; the tiling's full extent is visible
    /// as gaps around placed nodes. Reveals aperiodic structure.
    LeaveEmpty,
    /// Clip the layout bounds to the convex hull of used vertices.
    /// Tighter result; hides tiling periphery.
    ClipToHull,
    /// Hide the tiling backdrop entirely on platforms where the visual
    /// cost isn't worth it (mobile, low-power paths).
    HideTiling,
}

impl Default for UnusedVertexPolicy {
    fn default() -> Self {
        Self::LeaveEmpty
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct PenroseConfig {
    pub variant: PenroseVariant,
    pub subdivision_count: SubdivisionCount,
    pub assignment: NodeAssignmentStrategy,
    pub unused_vertices: UnusedVertexPolicy,
    pub center: Point2D<f32>,
    /// World-unit scale of the initial tile ring.
    pub tile_scale: f32,
}

impl Default for PenroseConfig {
    fn default() -> Self {
        Self {
            variant: PenroseVariant::default(),
            subdivision_count: SubdivisionCount::default(),
            assignment: NodeAssignmentStrategy::default(),
            unused_vertices: UnusedVertexPolicy::default(),
            center: Point2D::new(0.0, 0.0),
            tile_scale: 400.0,
        }
    }
}

/// Penrose aperiodic tiling layout.
#[derive(Debug, Default)]
pub struct Penrose {
    pub config: PenroseConfig,
}

impl Penrose {
    pub fn new(config: PenroseConfig) -> Self {
        Self { config }
    }
}

impl<N> Layout<N> for Penrose
where
    N: Clone + Eq + Hash,
{
    type State = StaticLayoutState;

    fn step(
        &mut self,
        scene: &CanvasSceneInput<N>,
        state: &mut Self::State,
        _dt: f32,
        _viewport: &CanvasViewport,
        extras: &LayoutExtras<N>,
    ) -> HashMap<N, Vector2D<f32>> {
        state.step_count = state.step_count.saturating_add(1);
        if scene.nodes.is_empty() {
            return HashMap::new();
        }

        let depth = match self.config.subdivision_count {
            SubdivisionCount::Explicit(d) => d,
            SubdivisionCount::Auto => choose_auto_depth(self.config.variant, scene.nodes.len()),
        };
        let vertices = build_tiling(self.config.variant, depth, self.config.tile_scale);
        if vertices.is_empty() {
            return HashMap::new();
        }
        let ordered = sort_center_out(vertices, self.config.center);

        let damping = state.damping.clamp(0.0, 1.0);
        let vertex_count = ordered.len();
        let mut deltas = HashMap::with_capacity(scene.nodes.len());
        // First-pass: all strategies other than PreservedOrder fall back
        // to the same preserved-order assignment. Advanced strategies
        // tracked as enrichment in the Step-5 plan.
        for (idx, node) in scene.nodes.iter().enumerate() {
            if extras.pinned.contains(&node.id) {
                continue;
            }
            if idx >= vertex_count {
                // More nodes than vertices — shouldn't happen with Auto
                // depth. Skip over-spilled nodes for now; future
                // enrichment could recurse for more vertices.
                break;
            }
            let target = ordered[idx];
            let delta = (target - node.position) * damping;
            if delta.length() > f32::EPSILON {
                deltas.insert(node.id.clone(), delta);
            }
        }
        deltas
    }
}

// ── Robinson triangle generation ─────────────────────────────────────────────

#[derive(Debug, Clone, Copy)]
enum TriangleKind {
    /// Golden-gnomon acute triangle (apex angle 36°). Called "L" or
    /// "thick" in P3; called "kite half" in P2.
    Acute,
    /// Golden-gnomon obtuse triangle (apex angle 108° for P3, or 72°
    /// for P2-dart). Called "S" or "thin" in P3; called "dart half" in
    /// P2.
    Obtuse,
}

#[derive(Debug, Clone, Copy)]
struct Triangle {
    kind: TriangleKind,
    a: Point2D<f32>, // apex
    b: Point2D<f32>,
    c: Point2D<f32>,
}

/// Generate the initial ring of triangles for a given variant.
///
/// Both P2 and P3 can be seeded with a ring of 10 triangles centered at
/// the origin — 5 "acute" mirrored-pair halves forming a regular
/// decagon. The subdivision rules differ, not the seed.
fn initial_ring(variant: PenroseVariant, scale: f32) -> Vec<Triangle> {
    let mut triangles = Vec::with_capacity(10);
    for i in 0..10 {
        let angle_a = i as f32 * std::f32::consts::TAU / 10.0;
        let angle_b = (i as f32 + 1.0) * std::f32::consts::TAU / 10.0;
        let a = Point2D::new(0.0, 0.0);
        let b = Point2D::new(scale * angle_a.cos(), scale * angle_a.sin());
        let c = Point2D::new(scale * angle_b.cos(), scale * angle_b.sin());
        let kind = if i % 2 == 0 {
            TriangleKind::Acute
        } else {
            TriangleKind::Obtuse
        };
        triangles.push(Triangle { kind, a, b, c });
    }
    let _ = variant;
    triangles
}

fn lerp(p: Point2D<f32>, q: Point2D<f32>, t: f32) -> Point2D<f32> {
    Point2D::new(p.x + (q.x - p.x) * t, p.y + (q.y - p.y) * t)
}

/// Subdivide a triangle according to P3 Robinson rules.
fn subdivide_p3(triangle: Triangle) -> Vec<Triangle> {
    match triangle.kind {
        TriangleKind::Acute => {
            // Acute(A, B, C): apex A, base BC. Split AB at P where
            // |AP| = |AB| / φ.
            let p = lerp(triangle.a, triangle.b, INV_PHI);
            vec![
                Triangle {
                    kind: TriangleKind::Acute,
                    a: triangle.c,
                    b: p,
                    c: triangle.a,
                },
                Triangle {
                    kind: TriangleKind::Obtuse,
                    a: p,
                    b: triangle.c,
                    c: triangle.b,
                },
            ]
        }
        TriangleKind::Obtuse => {
            // Obtuse(A, B, C): apex A, base BC. Split CB at Q where
            // |CQ| = |CB| / φ, and split AB at R analogously.
            let q = lerp(triangle.b, triangle.c, INV_PHI);
            vec![
                Triangle {
                    kind: TriangleKind::Obtuse,
                    a: q,
                    b: triangle.c,
                    c: triangle.a,
                },
                Triangle {
                    kind: TriangleKind::Acute,
                    a: q,
                    b: triangle.a,
                    c: triangle.b,
                },
            ]
        }
    }
}

/// Subdivide a triangle according to P2 kite-dart rules.
///
/// P2 uses the same Robinson triangle shapes as P3 but with different
/// subdivision rules. The visible difference in the tiling pattern comes
/// from the different adjacency pairings.
fn subdivide_p2(triangle: Triangle) -> Vec<Triangle> {
    match triangle.kind {
        TriangleKind::Acute => {
            // P2 kite half: split differently than P3 to produce the
            // kite-dart pattern rather than the rhombus pattern.
            let p = lerp(triangle.a, triangle.b, INV_PHI);
            let q = lerp(triangle.a, triangle.c, INV_PHI);
            vec![
                Triangle {
                    kind: TriangleKind::Obtuse,
                    a: p,
                    b: q,
                    c: triangle.a,
                },
                Triangle {
                    kind: TriangleKind::Acute,
                    a: q,
                    b: p,
                    c: triangle.b,
                },
                Triangle {
                    kind: TriangleKind::Acute,
                    a: triangle.c,
                    b: q,
                    c: triangle.b,
                },
            ]
        }
        TriangleKind::Obtuse => {
            // P2 dart half.
            let p = lerp(triangle.b, triangle.a, INV_PHI);
            vec![
                Triangle {
                    kind: TriangleKind::Obtuse,
                    a: p,
                    b: triangle.c,
                    c: triangle.a,
                },
                Triangle {
                    kind: TriangleKind::Acute,
                    a: triangle.c,
                    b: p,
                    c: triangle.b,
                },
            ]
        }
    }
}

fn subdivide(variant: PenroseVariant, triangle: Triangle) -> Vec<Triangle> {
    match variant {
        PenroseVariant::Rhombus => subdivide_p3(triangle),
        PenroseVariant::KiteDart => subdivide_p2(triangle),
    }
}

fn expand_tiling(variant: PenroseVariant, depth: u8, scale: f32) -> Vec<Triangle> {
    let mut tiles = initial_ring(variant, scale);
    for _ in 0..depth {
        let mut next = Vec::with_capacity(tiles.len() * 3);
        for tri in tiles.drain(..) {
            next.extend(subdivide(variant, tri));
        }
        tiles = next;
    }
    tiles
}

fn build_tiling(variant: PenroseVariant, depth: u8, scale: f32) -> Vec<Point2D<f32>> {
    let tiles = expand_tiling(variant, depth, scale);
    // Collect vertices, deduplicating by approximate equality (rounded
    // to 3 decimal places in world units).
    let mut seen: std::collections::HashSet<(i32, i32)> = std::collections::HashSet::new();
    let mut vertices = Vec::new();
    for tri in &tiles {
        for p in [tri.a, tri.b, tri.c] {
            let key = ((p.x * 1000.0).round() as i32, (p.y * 1000.0).round() as i32);
            if seen.insert(key) {
                vertices.push(p);
            }
        }
    }
    vertices
}

fn sort_center_out(mut vertices: Vec<Point2D<f32>>, center: Point2D<f32>) -> Vec<Point2D<f32>> {
    vertices.sort_by(|a, b| {
        let da = (*a - center).square_length();
        let db = (*b - center).square_length();
        da.partial_cmp(&db).unwrap_or(std::cmp::Ordering::Equal)
    });
    // Translate back to the configured center.
    for v in vertices.iter_mut() {
        v.x += center.x;
        v.y += center.y;
    }
    vertices
}

fn choose_auto_depth(variant: PenroseVariant, node_count: usize) -> u8 {
    // P3 expands ~φ² per step; P2 expands ~3×. Cap at 8 to bound memory
    // (P2 depth 8 ≈ 6500 tiles, P3 similar). Real graphs under 10k nodes
    // rarely need depth > 6. Count actual deduplicated vertices, since
    // tile_count × 3 overstates significantly.
    for depth in 0u8..=8 {
        let vertices = build_tiling(variant, depth, 1.0);
        if vertices.len() >= node_count {
            return depth;
        }
    }
    8
}

// Suppress unused-warning for PHI — it's documented/referenced above but
// not mechanically used since all ratios are expressed through INV_PHI.
#[allow(dead_code)]
const _: f32 = PHI;

#[cfg(test)]
mod tests {
    use super::*;
    use crate::scene::{CanvasEdge, CanvasNode};
    use euclid::default::{Rect, Size2D};

    fn viewport() -> CanvasViewport {
        CanvasViewport {
            rect: Rect::new(Point2D::new(0.0, 0.0), Size2D::new(1000.0, 1000.0)),
            scale_factor: 1.0,
        }
    }

    fn scene(n: u32) -> CanvasSceneInput<u32> {
        CanvasSceneInput {
            nodes: (0..n)
                .map(|id| CanvasNode {
                    id,
                    // Non-zero starting positions so zero-length deltas
                    // (node already at target) don't silently drop
                    // entries from the result map.
                    position: Point2D::new(10000.0 + id as f32, 10000.0),
                    radius: 16.0,
                    label: None,
                })
                .collect(),
            edges: Vec::<CanvasEdge<u32>>::new(),
        }
    }

    #[test]
    fn p3_subdivision_grows_triangle_count() {
        let d0 = expand_tiling(PenroseVariant::Rhombus, 0, 1.0).len();
        let d1 = expand_tiling(PenroseVariant::Rhombus, 1, 1.0).len();
        let d2 = expand_tiling(PenroseVariant::Rhombus, 2, 1.0).len();
        assert_eq!(d0, 10);
        assert!(d1 > d0);
        assert!(d2 > d1);
    }

    #[test]
    fn p2_subdivision_grows_triangle_count() {
        let d0 = expand_tiling(PenroseVariant::KiteDart, 0, 1.0).len();
        let d1 = expand_tiling(PenroseVariant::KiteDart, 1, 1.0).len();
        let d2 = expand_tiling(PenroseVariant::KiteDart, 2, 1.0).len();
        assert_eq!(d0, 10);
        assert!(d1 > d0);
        assert!(d2 > d1);
    }

    #[test]
    fn auto_depth_picks_depth_fitting_node_count() {
        let depth = choose_auto_depth(PenroseVariant::Rhombus, 50);
        // Depth 0 has 10 tiles = ~30 vertices (pre-dedup); depth 1+ should
        // exceed 50 easily.
        assert!(depth >= 1);
        let vertices = build_tiling(PenroseVariant::Rhombus, depth, 1.0);
        assert!(vertices.len() >= 50 || depth == 8);
    }

    #[test]
    fn penrose_places_nodes_near_center_first() {
        let mut layout = Penrose::new(PenroseConfig {
            variant: PenroseVariant::Rhombus,
            subdivision_count: SubdivisionCount::Explicit(3),
            center: Point2D::new(0.0, 0.0),
            tile_scale: 100.0,
            ..Default::default()
        });
        let mut state = StaticLayoutState::default();
        let input = scene(20);
        let deltas = layout.step(
            &input,
            &mut state,
            0.0,
            &viewport(),
            &LayoutExtras::default(),
        );

        // Node 0 (first in scene) should land nearest the center.
        let pos_0 = input.nodes[0].position + deltas[&0];
        let dist_0 = (pos_0 - Point2D::new(0.0, 0.0)).length();
        // Later nodes should be at least as far.
        for node in input.nodes.iter().skip(10) {
            if let Some(delta) = deltas.get(&node.id) {
                let pos = node.position + *delta;
                let dist = (pos - Point2D::new(0.0, 0.0)).length();
                assert!(
                    dist + 0.001 >= dist_0,
                    "node {:?} is closer than node 0",
                    node.id
                );
            }
        }
    }

    #[test]
    fn p2_and_p3_produce_different_vertex_sets() {
        let p2 = build_tiling(PenroseVariant::KiteDart, 3, 100.0);
        let p3 = build_tiling(PenroseVariant::Rhombus, 3, 100.0);
        let p2_keys: std::collections::HashSet<(i32, i32)> = p2
            .iter()
            .map(|p| ((p.x * 10.0) as i32, (p.y * 10.0) as i32))
            .collect();
        let p3_keys: std::collections::HashSet<(i32, i32)> = p3
            .iter()
            .map(|p| ((p.x * 10.0) as i32, (p.y * 10.0) as i32))
            .collect();
        assert_ne!(p2_keys, p3_keys, "P2 and P3 produce identical tilings");
    }

    #[test]
    fn pinned_nodes_skipped() {
        let mut layout = Penrose::new(PenroseConfig::default());
        let input = scene(4);
        let mut extras: LayoutExtras<u32> = LayoutExtras::default();
        extras.pinned.insert(0);
        let deltas = layout.step(
            &input,
            &mut StaticLayoutState::default(),
            0.0,
            &viewport(),
            &extras,
        );
        assert!(!deltas.contains_key(&0));
    }

    #[test]
    fn advanced_assignment_strategies_fall_back_in_first_pass() {
        // All non-PreservedOrder strategies should still produce a
        // deterministic assignment (same as PreservedOrder) in the
        // first-pass implementation.
        let mut layout_preserved = Penrose::new(PenroseConfig {
            assignment: NodeAssignmentStrategy::PreservedOrder,
            subdivision_count: SubdivisionCount::Explicit(2),
            ..Default::default()
        });
        let mut layout_graphlet = Penrose::new(PenroseConfig {
            assignment: NodeAssignmentStrategy::GraphletAware,
            subdivision_count: SubdivisionCount::Explicit(2),
            ..Default::default()
        });
        let input = scene(5);
        let deltas_preserved = layout_preserved.step(
            &input,
            &mut StaticLayoutState::default(),
            0.0,
            &viewport(),
            &LayoutExtras::default(),
        );
        let deltas_graphlet = layout_graphlet.step(
            &input,
            &mut StaticLayoutState::default(),
            0.0,
            &viewport(),
            &LayoutExtras::default(),
        );
        // Same assignment (first-pass).
        assert_eq!(deltas_preserved.len(), deltas_graphlet.len());
        for (key, d_pre) in &deltas_preserved {
            let d_graph = deltas_graphlet.get(key).unwrap();
            assert!((d_pre.x - d_graph.x).abs() < 0.01);
            assert!((d_pre.y - d_graph.y).abs() < 0.01);
        }
    }
}
