#!/usr/bin/env python3
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

"""
Capture reference fixture vectors for the BERT validation tier-1 test.

Run once on a machine with `sentence-transformers` available; copy the
printed Rust constant into `src/bert/validation.rs::FIXTURES`.

Usage:
    pip install sentence-transformers
    python scripts/capture_minilm_fixtures.py

This is the source-of-your-choice mentioned in the validation module
docs. Any other reference (candle-transformers, ort, etc.) that runs
the same MiniLM weights with mean-pool + L2-normalize should produce
identical fixtures within ~1e-4.

The committed fixtures are eight floats per reference text. They are
the artifact; this script disappears after the FIXTURES array is
populated. (Capturing additional reference texts is a one-line edit
to REFERENCE_TEXTS below.)
"""

import sys

REFERENCE_TEXTS = [
    "This is a sample sentence.",
    "The quick brown fox jumps over the lazy dog.",
    "Embeddings encode meaning into vector space.",
]


def main():
    try:
        from sentence_transformers import SentenceTransformer
    except ImportError:
        print(
            "error: sentence-transformers is not installed.\n"
            "  pip install sentence-transformers",
            file=sys.stderr,
        )
        sys.exit(1)

    model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")

    print("// Generated by scripts/capture_minilm_fixtures.py.")
    print("// Paste into src/bert/validation.rs in place of the empty FIXTURES.")
    print("pub const FIXTURES: &[Fixture] = &[")
    for text in REFERENCE_TEXTS:
        v = model.encode(text, normalize_embeddings=True)
        first_8 = list(v[:8])
        formatted = ", ".join(f"{x:.7e}" for x in first_8)
        # Escape the text for Rust string literal (basic).
        escaped = text.replace("\\", "\\\\").replace('"', '\\"')
        print(f'    Fixture {{ text: "{escaped}", first_8: [{formatted}] }},')
    print("];")


if __name__ == "__main__":
    main()
