/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/. */

//! Deterministic hash-based [`EmbeddingProvider`].
//!
//! Same input always produces the same vector; different inputs produce
//! different but uncorrelated vectors. Useful for testing pipelines and
//! demos that want stable embeddings without loading a model — but **not
//! semantically meaningful**: similar texts get unrelated vectors. Real
//! semantic similarity arrives with the Burn-backed BERT provider.
//!
//! The hash is FNV-1a 64-bit (deterministic, no allocations). The vector
//! is generated by a xorshift64 PRNG seeded with the hash, then
//! L2-normalized so cosine similarity is well-defined.

use crate::provider::{EmbedError, EmbeddingProvider, SimilarityMetric};

/// Deterministic hash-based embedding provider.
///
/// Construction takes the desired output dimension. `embed` is constant-time
/// per text (no model, no allocation beyond the output vector).
#[derive(Debug, Clone)]
pub struct HashedEmbeddingProvider {
    dimensions: usize,
}

impl HashedEmbeddingProvider {
    /// Construct with the desired output dimension. `dimensions` must be > 0.
    pub fn new(dimensions: usize) -> Result<Self, EmbedError> {
        if dimensions == 0 {
            return Err(EmbedError::InvalidConfig(
                "dimensions must be > 0".to_string(),
            ));
        }
        Ok(Self { dimensions })
    }
}

impl EmbeddingProvider for HashedEmbeddingProvider {
    fn dimensions(&self) -> usize {
        self.dimensions
    }

    fn metric(&self) -> SimilarityMetric {
        SimilarityMetric::Cosine
    }

    fn embed(&self, texts: &[&str]) -> Result<Vec<Vec<f32>>, EmbedError> {
        Ok(texts
            .iter()
            .map(|t| vector_from_seed(fnv1a_64(t), self.dimensions))
            .collect())
    }
}

/// FNV-1a 64-bit hash. Deterministic, allocation-free, byte-stable.
fn fnv1a_64(text: &str) -> u64 {
    const FNV_OFFSET: u64 = 0xcbf2_9ce4_8422_2325;
    const FNV_PRIME: u64 = 0x0000_0100_0000_01b3;
    let mut h = FNV_OFFSET;
    for byte in text.bytes() {
        h ^= byte as u64;
        h = h.wrapping_mul(FNV_PRIME);
    }
    h
}

/// xorshift64-driven L2-normalized vector. Components in `[-1, 1]` before
/// normalization; output has unit length so cosine similarity is meaningful.
fn vector_from_seed(seed: u64, dims: usize) -> Vec<f32> {
    // Avoid a zero seed (xorshift fixed point); replace with a known nonzero.
    let mut state = if seed == 0 {
        0x9e37_79b9_7f4a_7c15
    } else {
        seed
    };
    let mut vec = Vec::with_capacity(dims);
    for _ in 0..dims {
        state ^= state << 13;
        state ^= state >> 7;
        state ^= state << 17;
        // Map to [-1, 1).
        let raw = state as f64 / u64::MAX as f64;
        vec.push((raw * 2.0 - 1.0) as f32);
    }
    let norm: f32 = vec.iter().map(|x| x * x).sum::<f32>().sqrt();
    if norm > f32::EPSILON {
        for x in &mut vec {
            *x /= norm;
        }
    }
    vec
}

#[cfg(test)]
mod tests {
    use super::*;

    fn approx(a: f32, b: f32, eps: f32) -> bool {
        (a - b).abs() < eps
    }

    #[test]
    fn dimensions_must_be_positive() {
        assert!(HashedEmbeddingProvider::new(0).is_err());
        assert!(HashedEmbeddingProvider::new(1).is_ok());
        assert!(HashedEmbeddingProvider::new(384).is_ok());
    }

    #[test]
    fn metric_is_cosine() {
        let p = HashedEmbeddingProvider::new(64).unwrap();
        assert_eq!(p.metric(), SimilarityMetric::Cosine);
    }

    #[test]
    fn dimensions_match_constructor() {
        let p = HashedEmbeddingProvider::new(384).unwrap();
        let v = p.embed_one("anything").unwrap();
        assert_eq!(v.len(), 384);
        assert_eq!(p.dimensions(), 384);
    }

    #[test]
    fn deterministic_same_input() {
        let p = HashedEmbeddingProvider::new(64).unwrap();
        let a = p.embed_one("rust async").unwrap();
        let b = p.embed_one("rust async").unwrap();
        assert_eq!(a, b);
    }

    #[test]
    fn different_inputs_give_different_vectors() {
        let p = HashedEmbeddingProvider::new(64).unwrap();
        let a = p.embed_one("rust async").unwrap();
        let b = p.embed_one("python typing").unwrap();
        assert_ne!(a, b);
    }

    #[test]
    fn output_is_l2_normalized() {
        let p = HashedEmbeddingProvider::new(384).unwrap();
        let v = p.embed_one("the quick brown fox").unwrap();
        let norm: f32 = v.iter().map(|x| x * x).sum::<f32>().sqrt();
        assert!(approx(norm, 1.0, 1.0e-5), "norm={norm}");
    }

    #[test]
    fn batch_preserves_order() {
        let p = HashedEmbeddingProvider::new(32).unwrap();
        let texts = ["a", "b", "c", "d"];
        let batch = p.embed(&texts).unwrap();
        for (i, t) in texts.iter().enumerate() {
            let single = p.embed_one(t).unwrap();
            assert_eq!(batch[i], single, "mismatch at index {i} for text {t:?}");
        }
    }

    #[test]
    fn empty_input_handled() {
        let p = HashedEmbeddingProvider::new(8).unwrap();
        // Empty string is a valid input; embedding is still deterministic.
        let v = p.embed_one("").unwrap();
        assert_eq!(v.len(), 8);
    }

    #[test]
    fn batch_empty_returns_empty() {
        let p = HashedEmbeddingProvider::new(8).unwrap();
        let out = p.embed(&[]).unwrap();
        assert!(out.is_empty());
    }

    #[test]
    fn long_input_does_not_panic() {
        let p = HashedEmbeddingProvider::new(16).unwrap();
        let long: String = std::iter::repeat('x').take(10_000).collect();
        let v = p.embed_one(&long).unwrap();
        assert_eq!(v.len(), 16);
    }
}
